# Generated by Django 3.2.15 on 2023-02-01 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Адрес доставки')),
                ('normalized_address', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Нормализованый адрес')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8, null=True, verbose_name='Долгота')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата обновления')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
        ),
    ]
