# Generated by Django 3.2.16 on 2023-02-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='normalized_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='processed',
        ),
    ]
