# Generated by Django 3.2.15 on 2023-01-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'продукт в заказе', 'verbose_name_plural': 'продукты в заказе'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quamtity',
            new_name='quantity',
        ),
    ]
