# Generated by Django 3.2.15 on 2023-01-24 07:45

from django.db import migrations


class Migration(migrations.Migration):
    def fill_price(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        for item in OrderItem.objects.all().iterator():
            if not item.price:
                item.price = item.product.price
                item.save()
                
    dependencies = [
        ('foodcartapp', '0041_auto_20230124_0841'),
    ]

    operations = [
        migrations.RunPython(fill_price),
    ]
