# Generated by Django 3.2.15 on 2023-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230124_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новый'), (2, 'Готовится'), (3, 'Доставляется'), (4, 'Выполнен'), (5, 'Отменен')], db_index=True, default=1, verbose_name='статус'),
        ),
    ]
