# Generated by Django 3.2.15 on 2023-01-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новый'), (2, 'Готовится'), (3, 'Доставляется'), (4, 'Выполнен'), (5, 'Отменен')], db_index=True, default=1, verbose_name='Статус'),
        ),
    ]
